# Generated by Django 4.2.7 on 2024-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20241128_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('contrareembolso', 'Contra reembolso')], default='tarjeta', max_length=20),
        ),
    ]
