# Generated by Django 3.1.12 on 2024-11-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20241121_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='duration',
        ),
    ]
