# Generated by Django 5.1.3 on 2024-11-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_id_slug_shop_produc_id_f21274_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_id_f21274_idx',
        ),
    ]
