# Generated by Django 3.1.12 on 2024-11-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.duration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
