# Generated by Django 3.1.12 on 2024-11-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20241121_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_durations', to='shop.duration'),
        ),
    ]
