# Generated by Django 3.1.12 on 2024-11-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20241121_1959'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='id_idx',
        ),
        migrations.AlterField(
            model_name='duration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='product_id_slug_idx'),
        ),
    ]
