# Generated by Django 3.1.12 on 2024-11-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20241121_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
