# Generated by Django 3.1.12 on 2024-11-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20241121_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_inicio',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
